server:
  port: 8080
spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_acl?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    host: 192.168.92.128
    port: 6379
    database: 0
    password:
    timeout: 3000ms  #最大等待时间，超时则抛出异常，否则请求一直等待
  servlet:
    multipart:
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
# token配置
token:
  # 令牌自定义标识
  header: token
  # 令牌密钥
  secret: iewjfoeowijjweoifjfewifjewjijefi,,>>??
  # 令牌有效期（默认30分钟）  一秒为主
  expireTime: 18000000
jwt:
  tokenHeader: token
  secret: eiorjeowijfioewjfdksjfoisd
  expiration: 18000000
  tokenHead: Bearer

mybatis-plus:
  mapper-locations: classpath:com/xxl/springsecurity/mapper/xml/*.xml